/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Hana
 */
public class frame1 extends javax.swing.JFrame {

    /**
     * Creates new form frame1
     */
    public frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        diskon = new javax.swing.JTextField();
        barang2 = new javax.swing.JTextField();
        barang1 = new javax.swing.JTextField();
        barang3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta1 = new javax.swing.JTextArea();
        proses = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Pembayaran");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 30, 110, 14);

        jLabel2.setText("Barang 1");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(70, 80, 120, 14);

        jLabel3.setText("Barang 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(70, 120, 130, 14);

        jLabel4.setText("Barang 3");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 160, 150, 14);

        jLabel5.setText("Diskon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(70, 200, 120, 14);
        getContentPane().add(diskon);
        diskon.setBounds(180, 200, 160, 30);
        getContentPane().add(barang2);
        barang2.setBounds(180, 120, 160, 30);
        getContentPane().add(barang1);
        barang1.setBounds(180, 80, 160, 30);
        getContentPane().add(barang3);
        barang3.setBounds(180, 160, 160, 30);

        ta1.setColumns(20);
        ta1.setRows(5);
        jScrollPane1.setViewportView(ta1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(60, 270, 166, 96);

        proses.setText("proses");
        proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prosesActionPerformed(evt);
            }
        });
        getContentPane().add(proses);
        proses.setBounds(250, 240, 65, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void prosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prosesActionPerformed
        int br1 = Integer.parseInt(barang1.getText());
        int br2 = Integer.parseInt(barang2.getText());
        int br3 = Integer.parseInt(barang3.getText());
        double dis = Integer.parseInt(diskon.getText());
        double total = ((br1+br2+br3)*(dis/100)); 
        double  hasil = ((br1+br2+br3) - total);
        
        ta1.setText(String.valueOf(hasil));
        
        
        
    }//GEN-LAST:event_prosesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField barang1;
    private javax.swing.JTextField barang2;
    private javax.swing.JTextField barang3;
    private javax.swing.JTextField diskon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton proses;
    private javax.swing.JTextArea ta1;
    // End of variables declaration//GEN-END:variables
}
